# Generated by Django 2.1 on 2020-05-24 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestedQuote',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=10, null=True)),
                ('course_interested', models.CharField(db_column='course_interested', max_length=200)),
                ('created_time', models.DateTimeField(db_column='created_time', default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(db_column='modified_time', default=django.utils.timezone.now)),
                ('deleted_time', models.DateTimeField(blank=True, db_column='deleted_time', null=True)),
            ],
            options={
                'db_table': 'customer_requested_quote',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
